version: '3.8'
services:
  ewm-db:
    image: postgres:13
    container_name: ewm-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:13
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - stats_data:/var/lib/postgresql/data
    networks:
      - app-network

  stats-server:
    build: ./stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
    depends_on:
      - stats-db
    networks:
      - app-network

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      STATS_SERVER_URL: http://stats-server:9090
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    networks:
      - app-network

volumes:
  postgres_data:
  stats_data:

networks:
  app-network:
    driver: bridge